In [1]:
!pip install scipy

Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple


In [ ]:
import scipy
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
data = pd.read_csv('result_eva4.csv')

In [ ]:
data = data[data['name']=='cluster']

In [ ]:
data.to_csv('lstmdata.csv')

In [ ]:
data_time = data['time']

In [ ]:
data_time

47    2022-06-23
48    2022-06-22
49    2022-06-21
50    2022-06-20
51    2022-06-19
52    2022-06-18
53    2022-06-17
54    2022-06-16
55    2022-06-06
56    2022-06-05
57    2022-05-27
58    2022-05-26
59    2022-05-25
60    2022-05-24
61    2022-05-23
62    2022-05-22
63    2022-05-19
64    2022-05-18
65    2022-05-17
66    2022-05-13
67    2022-05-12
68    2022-05-11
69    2022-05-09
70    2022-05-08
71    2022-05-07
72    2022-05-06
73    2022-05-05
74    2022-05-04
75    2022-05-02
76    2022-05-01
77    2022-04-30
78    2022-04-27
79    2022-04-26
80    2022-04-25
81    2022-04-20
82    2022-04-19
83    2022-04-17
84    2022-04-16
85    2022-04-15
86    2022-04-14
87    2022-04-13
88    2022-04-12
89    2022-04-11
90    2022-04-10
91    2022-04-09
92    2022-04-08
93    2022-04-18
Name: time, dtype: object

In [ ]:
data_x = data['dcp']

In [ ]:
data_x =  data_x[:42]

In [ ]:
data_x = data_x[::-1]

In [ ]:
data_x = data_x.to_numpy()

In [ ]:
def np_move_avg(a,n,mode="same"):
    return(np.convolve(a, np.ones((n,))/n, mode=mode))

In [ ]:
def compute_fj(x,window):
    out = np_move_avg(x,window)
    out1 = x-out
    #length = len(x)//7
    out1 =out1- np.median(out1)
    return out1
    

In [ ]:
def compute_srbo(x):
    fft_y = scipy.fft.fft(x)
    abs_y=np.abs(fft_y)                # 取复数的绝对值，即复数的模(双边频谱)
    angle_y=np.angle(fft_y) 
    print(abs_y)
    l=np.log2(abs_y+0.001)
    kernel = np.ones(3)
    h = 1/9.*kernel
    print(h)
    hq=np.convolve(l, h, mode='same')
    r = l-hq
    out_put = r+1j*angle_y
    output = np.abs(scipy.fft.ifft(out_put))
    return output

In [ ]:
window = 7

In [ ]:
out = compute_fj(data_x,window)
out

array([ 226.43943733,   34.33970687,   42.0807783 ,  -51.9192217 ,
        274.29910714,  -79.88839286, -151.41517857,    9.15625   ,
        -69.70089286,  207.98660714,  -92.58482143,  -50.87053571,
         99.41517857,  -84.58482143,   23.70089286,   13.70089286,
         -9.15625   ,   91.49491279,   84.63776993, -194.81884707,
        -10.23412946,   75.18115293,  137.37747195,  -11.10456135,
         77.95462068, -170.3310936 , -125.16019089,   84.29596675,
         78.26838054, -100.01733374, -157.73161946, -109.15625   ,
        580.55803571,  214.84375   , -186.29910714, -129.15625   ,
        -51.15625   ,  -63.15625   ,   83.41517857,  129.70089286,
         93.12946429, -103.15625   ])

In [ ]:
output = compute_srbo(out)

[ 660.37820081  413.76791973  308.99299036  472.59124554  971.95600838
  805.30799087  788.01902639 1436.41569831 1429.57576653 1719.5604884
  595.43103805 1196.64655625 1400.48064306  452.14216885  947.31193876
  920.8378053   805.17247688  855.10671878  846.14773726  634.66581344
  455.45781218 1235.29755135  455.45781218  634.66581344  846.14773726
  855.10671878  805.17247688  920.8378053   947.31193876  452.14216885
 1400.48064306 1196.64655625  595.43103805 1719.5604884  1429.57576653
 1436.41569831  788.01902639  805.30799087  971.95600838  472.59124554
  308.99299036  413.76791973]
[0.11111111 0.11111111 0.11111111]


In [ ]:
o = np.argsort(-output)
o.shape

(42,)

In [ ]:
result = (output>1).astype(np.int8)

In [ ]:
result[o]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int8)

In [ ]:
np.save('pure_result.npy',output)
np.save('pure_label.npy',result)

In [ ]:
output[o]

array([6.46979311, 0.93840966, 0.67022166, 0.39703014, 0.33778707,
       0.30846907, 0.29177765, 0.27984899, 0.27371094, 0.24868968,
       0.24831122, 0.24429417, 0.21824332, 0.21628378, 0.21365489,
       0.20380928, 0.19690458, 0.18788406, 0.18567842, 0.17083678,
       0.1510483 , 0.14605935, 0.13454283, 0.12592147, 0.12488926,
       0.1210226 , 0.10372893, 0.10340371, 0.08602292, 0.08413307,
       0.07877165, 0.07074184, 0.06770585, 0.05978467, 0.04435907,
       0.0438193 , 0.0384173 , 0.02837703, 0.02461748, 0.02183149,
       0.01446431, 0.0107818 ])

In [ ]:
data_time = data_time[:42].to_numpy()

In [ ]:
data_time[o]

array(['2022-06-23', '2022-04-26', '2022-05-27', '2022-06-21',
       '2022-05-25', '2022-05-12', '2022-05-23', '2022-05-01',
       '2022-05-09', '2022-06-17', '2022-06-22', '2022-04-12',
       '2022-05-08', '2022-05-19', '2022-05-07', '2022-04-16',
       '2022-05-13', '2022-06-16', '2022-04-30', '2022-05-26',
       '2022-05-06', '2022-04-17', '2022-04-27', '2022-06-20',
       '2022-04-13', '2022-05-04', '2022-04-20', '2022-04-19',
       '2022-05-22', '2022-05-17', '2022-04-15', '2022-06-19',
       '2022-05-24', '2022-05-05', '2022-04-25', '2022-05-11',
       '2022-05-02', '2022-06-06', '2022-06-05', '2022-06-18',
       '2022-05-18', '2022-04-14'], dtype=object)